name: Build Distributable Apps
on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with: 
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install mitmproxy

      - name: Build main with PyInstaller
        run: pyinstaller --onedir --windowed --icon=src/icon/icon.icns src/MyWatchDog.py

      - name: Build encoder with PyInstaller
        run: pyinstaller --onefile --console --icon=src/icon/icon.icns src/GetCode.py
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-executable
          path: dist/
          
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with: 
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install mitmproxy

      - name: Build main with PyInstaller
        run: pyinstaller --onedir --windowed --icon=src/icon/icon.ico src/MyWatchDog.py

      - name: Build encoder with PyInstaller
        run: pyinstaller --onefile --console --icon=src/icon/icon.ico src/GetCode.py
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-executable
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with: 
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install mitmproxy

      - name: Build main with PyInstaller
        run: pyinstaller --onedir --windowed src/MyWatchDog.py

      - name: Build encoder with PyInstaller
        run: pyinstaller --onefile --console src/GetCode.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-executable
          path: dist/
